# Generated by Django 5.1.6 on 2025-02-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_em", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "dish")},
        ),
    ]
