# Generated by Django 5.1.6 on 2025-02-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_em", "0002_alter_orderitem_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Dish"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Order Item"},
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "dish"), name="unique_order_dish"
            ),
        ),
    ]
