# Generated by Django 5.1.6 on 2025-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_em", "0003_alter_dish_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер стола"),
        ),
    ]
