# Generated by Django 5.1.6 on 2025-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_em", "0004_alter_order_table_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("ready", "Ready"), ("paid", "Paid")],
                default="waiting",
                max_length=10,
                verbose_name="Статус заказа",
            ),
        ),
    ]
