# Generated by Django 5.1.6 on 2025-02-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_em", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("в ожидании", "Waiting"),
                    ("готово", "Ready"),
                    ("оплачено", "Paid"),
                ],
                default="в ожидании",
                max_length=10,
                verbose_name="Статус заказа",
            ),
        ),
    ]
